### ISSUE TITLE
Create User Context

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife2.0#2]
## Description
 Create a User Context to handle user login/logout and permissions.
## Tasks
- [ ] Define the user context schema
- [ ] Create the User Context and provide a default implementation
- [ ] Implement login/logout functionality in the User Context
- [ ] Define the user permissions schema
- [ ] Add permissions to the User Context schema
- [ ] Implement permissions handling in the User Context
- [ ] Update the application to use the User Context
- [ ] Modify features to use user context to restrict access or enable specific functionality
## Accept Criteria
1. The User Context is created and can handle user login/logout functionality.
2. The User Context can handle user permissions and restrict access to certain features based on the user's permissions.
3. The application integrates with the User Context, and user-specific functionality works as expected.
