### ISSUE TITLE
Navegation bar

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/codelife2.0#6]
##Description
Create a Navbar component 
##Tasks
- [ ] Create styles to navbar using tailwindCSS
- [ ] Change if has a user in the authContext
- [ ] Create a CodelifeIcon Component
- [ ] Install a icon library
- [ ] utilize the icon library to make a beautiful navbar
##Acceptance Criteria
1. Nice criteria
